Decreasing the length of the text and improving consistency of the narrative: `03.use-cases-b.md`
SORTEE-Github-Hackathon/manuscript pull request #241
Opened 2022-06-17 22:23 UTC by pedrohbraga

Hi, again

This part continues with the changes to make the text more concise to meet journal requirements (the objective is to decrease the length from 6,250 words to 4,000 words).

I have done my best to keep the information you carefully worked for and included in the manuscript, but some examples and some sentences needed to be taken away so we can meet journal requirements.

I have also added citations and text that could support the discussion in these parts.

I have tagged the contributors to the sections I am changing so they can read and approve these modifications. Others are also encouraged to provide feedback if they would like to.

If you would like to make a change to the file in this pull request, please make it directly here.

Do not hesitate to comment on these changes here or let me know if there are any issues!

2022-06-19 19:01 UTC, DrMattG requested changes
SOme minor suggests to text - good job in reducing it!

2022-06-19 19:01 UTC, DrMattG commented on content/04.use-cases-b.md
> +GitHub can also serve to reviewers and authors during the peer review process.
"can aslo assist reviewers" (?) I am not sure if that is what is meant - maybe "serve reviewers" could work but not with the addition of "to"

2022-06-23 16:54 UTC, robcrystalornelas approved these changes

2022-06-23 16:56 UTC, robcrystalornelas commented
@DrMattG I made your suggested changes as well as a few of my own. Hoping you will be able to review. Thanks!

2022-06-23 17:29 UTC, DrMattG approved these changes

2022-06-23 17:30 UTC, merged